# Generated by Django 5.1.3 on 2024-11-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('idobservacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigoestacion', models.CharField(max_length=50)),
                ('codigosensor', models.CharField(max_length=50)),
                ('fechaobservacion', models.DateField()),
                ('valorobservado', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('codigosensor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcionsensor', models.CharField(max_length=50)),
                ('unidadmedida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('codigoestacion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombreestacion', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('zonahidrografica', models.CharField(max_length=50)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='department',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastname',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='municipality',
            new_name='departmento',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='latitude',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='longitude',
            new_name='longitud',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='municipio',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='phone',
            new_name='telefono',
        ),
    ]
