# Generated by Django 5.1.3 on 2024-11-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0003_alter_stations_codigoestacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='codigoestacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='observations',
            name='codigosensor',
            field=models.CharField(max_length=100),
        ),
    ]
