# Generated by Django 5.1.3 on 2024-11-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0004_alter_observations_codigoestacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='fechaobservacion',
            field=models.DateTimeField(),
        ),
    ]
