# Generated by Django 5.1.3 on 2024-11-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0006_remove_users_latitud_remove_users_longitud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='direccion',
            new_name='addrest',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='apellido',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='contraseña',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='departmento',
            new_name='municipaly',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='municipio',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='nombre',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='telefono',
            new_name='phone',
        ),
    ]
