# Generated by Django 5.1.3 on 2024-11-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0007_rename_direccion_users_addrest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='municipaly',
            new_name='municipality',
        ),
    ]
