# Generated by Django 5.1.3 on 2024-11-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0008_rename_municipaly_users_municipality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='addrest',
            new_name='address',
        ),
    ]
