# Generated by Django 5.1.3 on 2024-11-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0011_alter_meetingpoint_nombresede'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingPoint',
        ),
    ]
