# Generated by Django 5.1.3 on 2024-11-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0013_meetingpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingpoint',
            name='departamentoSedeDesc',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='meetingpoint',
            name='direccionSede',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meetingpoint',
            name='emailSede',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meetingpoint',
            name='municipioSedeDesc',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='meetingpoint',
            name='nombreSede',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meetingpoint',
            name='telefonoSede',
            field=models.CharField(max_length=100),
        ),
    ]
