# Generated by Django 5.1.3 on 2024-11-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0016_modelosprediccionprecipitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('idprediccion', models.AutoField(primary_key=True, serialize=False)),
                ('valorpredicciontoday', models.FloatField()),
                ('valorpredicciontomorrow', models.FloatField()),
                ('valorprediccionaftertomorrow', models.FloatField()),
                ('municipioprediccion', models.CharField(max_length=50)),
                ('departamentoprediccion', models.CharField(max_length=50)),
            ],
        ),
    ]
